baseURL = "https://kimlehtinen.com/"
# title = "Kim Lehtinen"
author = "Kim Lehtinen"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-kiera"
title = "Kim Lehtinen"

[permalinks]
  blog = '/:slug/'

[params]
  color = 'linen'

  twitter = 'kimlehtinen'
  github = 'kimlehtinen'
  linkedin = 'kim-lehtinen'
  rss = ''
  #instagram = 'nan.xiaobei'
  mail = 'kim@kimlehtinen.com'

  avatar = 'kim@kimlehtinen.com'
  name = 'Kim Lehtinen'
  bio = "Hello! I'm Kim Lehtinen, a Software Engineer trying to make the world a better place through technology. I focus on backend and cloud technologies, and most of my experience is in industrial and energy sector."
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 11
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 12
#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 14

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
