# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://kimlehtinen.com"

# The name of this wonderful theme ;-).
theme = 'kimlehtinen'

# Basic metadata configuration for your blog.
title = "Kim Lehtinen"
author = "Kim Lehtinen"

copyright = "Copyright © 2024, Kim Lehtinen."
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'english'
    title = 'Kim Lehtinen'
    weight = 1
    [languages.en.pagination]
      disableAliases = true
      pagerSize = 5
      path = 'page'
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 30

    [[languages.en.menu.footer]]
      identifier = "home"
      name = "Home"
      url = "/"
      weight = 10
    [[languages.en.menu.footer]]
      identifier = "blog"
      name = "Blog"
      url = "/blog/"
      weight = 20
    [[languages.en.menu.footer]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 30
    [[languages.en.menu.footer]]
      identifier = "blogroll"
      name = "Blogroll"
      url = "/blogroll/"
      weight = 40

    [languages.en.params]
      title = "Kim Lehtinen"
      copyright = "Copyright &copy; 2024 - Kim Lehtinen"
      #subtitle = 'Software, Cloud & Engineering'
      path = '/'
      name = 'Kim Lehtinen'
      author = "Kim Lehtinen"
      siteimage = "/images/kimlehtinen.jpg"
      description = "Kim Lehtinen is a Software Engineer specializing in backend and cloud technologies."
      #summaryLength = 50
      bio = 'Hello! I’m Kim Lehtinen, a Software Engineer trying to make the world a better place through technology. I mostly work with backend and cloud technologies, and most of my experience is in industrial sector. I help companies gain a competitive advantage through software, automation & cloud.'

      [languages.en.params.consent]
        [[languages.en.params.consent.services]]
          title = "Google Analytics (non-functional)"
          description = "This code gives us insight into the number of people that visit our website, where they are from and what they are clicking on. This helps us to improve our website and provide better content."
          is_functional = false
          script_file = "ga.js"

  [languages.fi]
    contentDir = 'content/fi'
    disabled = false
    languageCode = 'fi-FI'
    languageDirection = 'ltr'
    languageName = 'suomi'
    title = 'Kim Lehtinen'
    weight = 2
    [languages.fi.pagination]
      disableAliases = true
      pagerSize = 5
      path = 'page'
    [languages.fi.menu]
      [[languages.fi.menu.main]]
        identifier = "home"
        name = "Koti"
        url = "/fi"
        weight = 10
      #[[languages.fi.menu.main]]
      #  identifier = "blog"
      #  name = "Blogi"
      #  url = "/fi/blogi/"
      #  weight = 20
      [[languages.fi.menu.main]]
        identifier = "about"
        name = "Minusta"
        url = "/fi/minusta/"

    [[languages.fi.menu.footer]]
      identifier = "home"
      name = "Koti"
      url = "/fi"
      weight = 10
    [[languages.fi.menu.footer]]
      identifier = "about"
      name = "Minusta"
      url = "/fi/minusta/"
      weight = 20
    [[languages.fi.menu.footer]]
      identifier = "blogiluettelo"
      name = "Blogiluettelo"
      url = "/fi/blogiluettelo/"
      weight = 30

    [languages.fi.params]
      title = "Kim Lehtinen"
      author = "Kim Lehtinen"
      siteimage = "/images/kimlehtinen.jpg"
      copyright = "Copyright &copy; 2024 - Kim Lehtinen"
      #subtitle = 'Software, Cloud & Engineering'
      path = '/fi'
      name = 'Kim Lehtinen'
      description = ""
      #summaryLength = 50
      bio = 'Hei! Olen Kim Lehtinen, ohjelmistokehittäjä, joka pyrkii parantamaan maailmaa teknologian avulla. Työskentelen pääasiassa backend- ja pilviteknologioiden parissa, ja suurin osa kokemuksestani on teollisuusalalta. Autan yrityksiä saavuttamaan kilpailuetua ohjelmistojen, automaation ja pilvipalveluiden avulla.'

      [languages.fi.params.consent]
        [[languages.fi.params.consent.services]]
          title = "Google Analytics (ei-toiminnallinen)"
          description = "Tämä koodi antaa meille tietoa siitä, kuinka monta ihmistä vierailee verkkosivuillamme, mistä he ovat kotoisin ja mihin he klikkaavat. Tämä auttaa meitä parantamaan verkkosivujamme ja tarjoamaan parempaa sisältöä."
          is_functional = false
          script_file = "ga.js"

  [languages.sv]
    contentDir = 'content/sv'
    disabled = false
    languageCode = 'sv-SE'
    languageDirection = 'ltr'
    languageName = 'svenska'
    title = 'Kim Lehtinen'
    weight = 2
    [languages.sv.pagination]
      disableAliases = true
      pagerSize = 5
      path = 'page'
    [languages.sv.menu]
      [[languages.sv.menu.main]]
        identifier = "home"
        name = "Hem"
        url = "/sv"
        weight = 10
      #[[languages.sv.menu.main]]
      #  identifier = "blog"
      #  name = "Blogg"
      #  url = "/sv/blogg/"
      #  weight = 20
      [[languages.sv.menu.main]]
        identifier = "about"
        name = "Om mig"
        url = "/sv/om-mig/"

    [[languages.sv.menu.footer]]
      identifier = "home"
      name = "Hem"
      url = "/sv"
      weight = 10
    [[languages.sv.menu.footer]]
      identifier = "about"
      name = "Om mig"
      url = "/sv/om-mig/"
      weight = 20
    [[languages.sv.menu.footer]]
      identifier = "blogglista"
      name = "Blogglista"
      url = "/sv/blogglista/"
      weight = 30

    [languages.sv.params]
      title = "Kim Lehtinen"
      author = "Kim Lehtinen"
      siteimage = "/images/kimlehtinen.jpg"
      copyright = "Copyright &copy; 2024 - Kim Lehtinen"
      #subtitle = 'Software, Cloud & Engineering'
      path = '/sv'
      name = 'Kim Lehtinen'
      description = ""
      #summaryLength = 50
      bio = 'Hej! Jag är Kim Lehtinen, en mjukvaruingenjör som försöker göra världen till en bättre plats genom teknologi. Jag arbetar främst med backend- och molnteknologier, och största delen av min erfarenhet är inom industrisektorn. Jag hjälper företag att få konkurrensfördelar genom mjukvara, automation och molntjänster.'

      [languages.sv.params.consent]
        [[languages.sv.params.consent.services]]
          title = "Google Analytics (icke-funktionell)"
          description = "Denna kod ger oss insikt i antalet personer som besöker vår webbplats, var de kommer ifrån och vad de klickar på. Detta hjälper oss att förbättra vår webbplats och tillhandahålla bättre innehåll."
          is_functional = false
          script_file = "ga.js"

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/tag/:slug"
  categories = "/category/:slug"

[params]
  [params.social]
    name = "Kim Lehtinen"
    github = "kimlehtinen"
    gitlab = ""
    linkedin = "kimlehtinen"
    facebook = ""
    twitter = "kimlehtinen"
    instagram = ""
    rss = "/index.xml"
    bluesky = "kimlehtinen.com"
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Kim Lehtinen is a Software Engineer specializing in backend and cloud technologies."

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "favicon.ico"
  #summaryLength = 50
  # These "images" are used for the structured data templates. This will show up, when
  # services like Twitter or Slack want to generate a preview of a link to your site.
  # See https://gohugo.io/templates/internal#twitter-cards and
  # https://gohugo.io/templates/internal#open-graph.
  images = ["images/kimlehtinen.jpg"]

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Kim Lehtinen"
  copyright = "Copyright &copy; 2024 - Kim Lehtinen"
  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  hideMadeWithLine = true

  [[params.tagAliases]]
    name = "C++"
    slug = "cpp"

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  # dateFormat = "2006-01-02"